networks:
  trust_me_bro:

secrets:
  google_client_id_secret:
    environment: GOOGLE_CLIENT_ID

services:
  backend:
    build: ./backend
    image: ft-transcendence-backend
    restart: always
    networks:
      - trust_me_bro
    volumes:
      - ./backend/database:/app/database:rw,z
  frontend:
    build:
      context: ./frontend
      secrets:
        - google_client_id_secret
    image: ft-transcendence-frontend
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: always
    networks:
      - trust_me_bro