CREATE TABLE IF NOT EXISTS USER (
  EMAIL TEXT PRIMARY KEY NOT NULL,
  USERNAME TEXT UNIQUE NOT NULL,
  AVATAR BLOB,
  RATING INTEGER NOT NULL DEFAULT 0,
  WINNING_STREAK INTEGER NOT NULL DEFAULT 0,
  TOTAL_WIN INTEGER NOT NULL DEFAULT 0,
  TOTAL_LOSE INTEGER NOT NULL DEFAULT 0
);