CREATE TABLE IF NOT EXISTS FRIEND_LIST (
    USER_EMAIL TEXT NOT NULL,
    FRIEND_EMAIL TEXT NOT NULL,
    PRIMARY KEY (USER_EMAIL, FRIEND_EMAIL),
    FOREIGN KEY (USER_EMAIL) REFERENCES USER(EMAIL) ON DELETE CASCADE,
    FOREIGN KEY (FRIEND_EMAIL) REFERENCES USER(EMAIL) ON DELETE CASCADE
);
