CREATE TABLE IF NOT EXISTS USER (
  EMAIL TEXT PRIMARY KEY NOT NULL,
  USERNAME TEXT UNIQUE NOT NULL,
  AVATAR BLOB,
  RATING INTEGER NOT NULL,
  WINNING_STREAK INTEGER NOT NULL,
  TOTAL_WIN INTEGER NOT NULL,
  TOTAL_LOSE INTEGER NOT NULL
);